#! /usr/bin/env python

print ("True")
print("#True")
print ("False")
print("#False")
print (2>1)
print('#True')
print (2<1)
print('#False')
print( 5==5 )
print('#True')
print(5!=4)
print('#True')
print('Python' == 'Python')
print('#True')
print('Python' == 'python')
print('#False')
print('Python' != 'python')
print('#True')
print(2>1 and 5==5)
print('#True')
print(2>1 and 5!=5)
print('#False')
print(2>1 or 5==5)
print('#True')
print(2>1 or 5!=5)
print('#True')
print(2<1 or 5!=5)
print('#False')


